# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - pkg/gieenm-system/graphql/schemas/*.graphql

# Where should the generated server code go?
exec:
  filename: pkg/gieenm-system/graphql/internal.go
  package: gql

# Uncomment to enable federation
# federation:
#   filename: graph/generated/federation.go
#   package: generated

# Where should any generated models go?
model:
  filename: pkg/gieenm-system/graphql/models_example.go
  package: gql

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: pkg/gieenm-system/graphql/resolvers
  package: resolvers

# Optional: turn on use `gqlgen:"fieldName"` tags in your models
struct_tag: gqlgen

# Optional: turn on to use []Thing instead of []*Thing
omit_slice_element_pointers: false

# Optional: set to speed up generation time by not performing a final validation pass.
# skip_validation: true

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
autobind:
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/graphql/base"
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/announcement"
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/viewer"
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/user"
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/authentication"
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/firewall"
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/firewall/record"
  - "github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/firewall/group"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
  Int64:
    model:
      - github.com/99designs/gqlgen/graphql.Int64
  Float:
    model:
      - github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/graphql/scalars.Float
  Float64:
    model:
      - github.com/99designs/gqlgen/graphql.Float
  Upload:
    model:
      - github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/graphql/scalars.Upload
  IPAddr:
    model:
      - github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/graphql/scalars.IPAddr
  MacAddr:
    model:
      - github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/graphql/scalars.MacAddr
  Role:
    model:
      - github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/user.Role
  AnnounceLevel:
    model:
      - github.com/cliffxzx/gieenm-tools/pkg/gieenm-system/announcement.AnnounceLevel
